### ISSUE TITLE
virtual methods

### ISSUE THREAD

**Issue by hayguen** [DFHack/clsocket#3]
most methods in the classes are virtual.
i don't see any obvious reason for this - and tend to remove the "virtual" keyword!
am i wrong?

**Comment by lethosor** [comment]
There are a couple methods that are overridden by CSimpleSocket subclass (e.g. CPassiveSocket::Send). I'm not sure if there's anywhere that works with CSimpleSocket objects generically and would need methods to be virtual, but because there are some that aren't virtual, I'm assuming there was a reason for making them virtual besides the original author liking virtual methods. It looks like he was looking into a specialized HTTP socket class at one point, which would make some of those virtual methods useful. That's probably not anything that we'll work with, but if someone does decide to subclass CSimpleSocket for some reason, keeping methods virtual would make it somewhat easier.

If there's anything that obviously shouldn't be virtual, though, please feel free to bring it up (e.g. `IsNonblocking()`, although that's already non-virtual).
